<template><section class="requests"><header><div><h2>我的服务单</h2><p>查看审核回复、补充材料并下载文件。进度每 5 秒自动同步。</p></div><button @click="$emit('close')">返回对话</button><button :disabled="loading" @click="load">刷新</button></header><p v-if="error" role="alert">{{ error }}</p><p v-if="loading">正在加载…</p><p v-else-if="!rows.length">暂无申请。返回对话说“我要办理人事变更”即可开始。</p><article v-for="row in rows" :key="row.id"><h3>#{{ row.id }} · {{ row.label }}</h3><strong>{{ row.statusLabel }}</strong><details><summary>查看申请内容</summary><p v-for="(value,key) in row.fields" :key="key">{{ key }}：{{ value }}</p></details><p v-if="row.opinion">审核回复：{{ row.opinion }}</p><div v-if="row.kind !== 'LEAVE' && !row.certificateRequestId && ['DRAFT','SUBMITTED','NEEDS_INFO'].includes(row.status)"><label>在线补充材料（PDF，最多 5 MB）<input type="file" accept=".pdf,application/pdf" :disabled="busy" @change="upload(row.id,$event)"/></label><p>{{ row.materialsName ? '已上传材料包，再次上传会替换' : '仅提交办理所需材料，加密保存供 HR 核验' }}</p></div><form v-if="row.status==='NEEDS_INFO'" @submit.prevent="supplement(row.id)"><label>补充说明<textarea v-model="extra[row.id]" maxlength="1000" required/></label><button :disabled="busy">确认补充并重新提交</button></form><p v-if="row.certificateRequestId"><a href="/certificates" @click.prevent="$emit('open', '证明管理', '/certificates')">查看原有证明申请、资料要求及模板</a></p><p v-if="row.certificateFileName && !row.certificateSigned">正式电子签章尚未完成，当前可查看未签章预览。</p><button v-if="row.certificateFileName" :disabled="busy" @click="previewCertificate(row)">查看完整证明</button><button v-if="row.certificateFileName" :disabled="busy" @click="downloadPdf(row)">{{ row.certificateSigned ? '下载已签章 PDF' : '下载未签章预览 PDF' }}</button><button v-if="row.certificateFileName" :disabled="busy" @click="downloadCertificate(row)">下载 Word 原稿</button><button v-if="row.fileName" :disabled="busy" @click="download(row.id)">下载交付文件</button><p v-if="row.leaveRequestId">请假状态与审批记录同步。</p></article><div v-if="previewUrl" class="pdf-overlay" role="dialog" aria-modal="true" aria-label="证明完整预览"><header><div><strong>{{ previewName }}</strong><p>{{ previewSigned ? '电子签章已完成' : '未签章预览，正式签章仍在等待企业电子签配置或处理' }}</p></div><button @click="closePreview">关闭预览</button></header><iframe :src="previewUrl" title="在职证明 PDF 完整页面"></iframe></div></section></template>
<script setup lang="ts">
import {onMounted,onBeforeUnmount,reactive,ref} from 'vue'
import {serviceRequest,apiErrorMessage,uploadLifecycleMaterials,certificatePdf} from '../api'
import type {AuthSession} from '../types'
const props=defineProps<{session:AuthSession}>();defineEmits<{close:[];open:[title:string,path:string]}>()
const previewUrl=ref(''),previewName=ref(''),previewSigned=ref(false)
const rows=ref<any[]>([]),loading=ref(false),busy=ref(false),error=ref(''),extra=reactive<Record<number,string>>({})
async function load(){loading.value=true;error.value='';try{rows.value=await serviceRequest(props.session,'/lifecycle/mine')}catch(e){error.value=apiErrorMessage(e)}finally{loading.value=false}}
async function supplement(id:number){if(busy.value)return;busy.value=true;error.value='';try{await serviceRequest(props.session,`/lifecycle/${id}/supplement`,{method:'POST',body:{text:extra[id]}});extra[id]='';await load()}catch(e){error.value=apiErrorMessage(e)}finally{busy.value=false}}
async function download(id:number){if(busy.value)return;busy.value=true;error.value='';try{const blob=await serviceRequest(props.session,`/lifecycle/${id}/file`,{binary:true});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`服务单-${id}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){error.value=apiErrorMessage(e)}finally{busy.value=false}}
async function upload(id:number,event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file||busy.value)return;busy.value=true;error.value='';try{await uploadLifecycleMaterials(props.session,id,file);await load()}catch(e){error.value=apiErrorMessage(e)}finally{busy.value=false}}
function closePreview(){if(previewUrl.value)URL.revokeObjectURL(previewUrl.value.split('#')[0]);previewUrl.value=''}
async function previewCertificate(row:any){if(busy.value)return;busy.value=true;error.value='';try{const result=await certificatePdf(props.session,row.certificateRequestId);closePreview();previewName.value=result.name;previewSigned.value=result.signed;previewUrl.value=URL.createObjectURL(result.blob)+'#view=FitH'}catch(e){error.value=apiErrorMessage(e)}finally{busy.value=false}}
async function downloadPdf(row:any){if(busy.value)return;busy.value=true;error.value='';try{const result=await certificatePdf(props.session,row.certificateRequestId);const url=URL.createObjectURL(result.blob),a=document.createElement('a');a.href=url;a.download=result.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(e){error.value=apiErrorMessage(e)}finally{busy.value=false}}
async function downloadCertificate(row:any,signed=false){if(busy.value)return;busy.value=true;error.value='';try{const blob=await serviceRequest(props.session,`/employment-certificates/${row.certificateRequestId}/${signed?'signed-document':'download'}`,{binary:true});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=signed?`在职证明-${row.certificateRequestId}-已盖章.pdf`:row.certificateFileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){error.value=apiErrorMessage(e)}finally{busy.value=false}}
let alive=true,refreshing=false,timer:ReturnType<typeof setInterval>
async function refresh(){if(!alive||busy.value||loading.value||refreshing||document.hidden)return;refreshing=true;const current=props.session;try{const data=await serviceRequest(current,'/lifecycle/mine');if(alive&&props.session===current){rows.value=data;error.value=''}}catch{if(alive)error.value='进度同步暂时中断，连接恢复后会自动重试。'}finally{refreshing=false}}
onMounted(()=>{void load();timer=setInterval(refresh,5000);document.addEventListener('visibilitychange',refresh)})
onBeforeUnmount(()=>{closePreview();alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',refresh)})
</script>
<style scoped>.requests{height:100%;overflow:auto;padding:24px;box-sizing:border-box}.requests header{display:flex;gap:16px;align-items:center;flex-wrap:wrap}.requests h2{margin:0}.requests p{line-height:1.7;white-space:pre-wrap;overflow-wrap:anywhere}.requests article{border:1px solid #dce5e2;border-radius:12px;margin:20px 0;padding:20px}.requests button{border:1px solid #b5cdc4;border-radius:8px;background:#f3f9f6;padding:10px;color:#22634d;cursor:pointer}.requests label{display:grid;gap:8px}.requests textarea{min-height:90px;max-width:100%;padding:12px;font:inherit}.requests form{display:grid;gap:12px}.requests summary{cursor:pointer;margin-top:14px}.requests button:disabled{opacity:.5;cursor:wait}</style>

<style scoped>.pdf-overlay{position:fixed;inset:20px;z-index:500;background:#fff;border-radius:16px;box-shadow:0 0 0 100vmax #102c3980;display:flex;flex-direction:column;overflow:hidden}.pdf-overlay header{padding:14px 20px;border-bottom:1px solid #dce5e2;display:flex;justify-content:space-between}.pdf-overlay header p{font-size:13px;margin:6px 0;color:#556d62}.pdf-overlay iframe{width:100%;flex:1;border:0;background:#eef3ef}</style>
